const gyms = [
  {
    name: "FitPro Gym Premium",
    location: "вул. Спортивна, 10, Київ",
    price: "890 грн",
    rating: 5.0,
    features: ["Тренажерний зал", "Кросфіт", "Тренери"],
    description: "Сучасний преміум спортзал з великим вибором тренажерів, просторою зоною для кросфіту та професійними тренерами.",
    image: "./src/images/gym.jpg",
    hours: "07:00 - 23:00",
  },
  {
    name: "Yoga Life Studio",
    location: "вул. Затишна, 5, Київ",
    price: "360 грн",
    rating: 4.8,
    features: ["Йога", "Медитація", "Пілатес"],
    description: "Затишна студія йоги з різноманітними напрямками практик та досвідченими інструкторами.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 21:00",
  },
  {
    name: "Aqua Sport Elite",
    location: "пр. Перемоги, 25, Київ",
    price: "750 грн",
    rating: 4.7,
    features: ["Басейн", "Аквааеробіка", "Сауна"],
    description: "Елітний спортивний комплекс з басейном, аквааеробікою та різноманітними водними програмами для дорослих і дітей.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 22:00",
  },
  {
    name: "Iron Gym Classic",
    location: "вул. Залізна, 15, Львів",
    price: "420 грн",
    rating: 4.9,
    features: ["Тренажерний зал", "Силові тренування"],
    description: "Ідеальне місце для любителів важкої атлетики та силових тренувань.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 22:00",
  },
  {
    name: "Wellness Center Deluxe",
    location: "вул. Здоров'я, 12, Одеса",
    price: "980 грн",
    rating: 4.6,
    features: ["Спа", "Масаж", "Йога"],
    description: "Центр здоров'я та релаксації з професійними послугами спа та масажу.",
    image: "./src/images/gym.jpg",
    hours: "09:00 - 20:00",
  },
  {
    name: "CrossFit Arena Pro",
    location: "вул. Арена, 8, Харків",
    price: "520 грн",
    rating: 4.7,
    features: ["Кросфіт", "Групові тренування"],
    description: "Спеціалізований зал для кросфіту з професійними тренерами.",
    image: "./src/images/gym.jpg",
    hours: "07:00 - 22:00",
  },
  {
    name: "PowerHouse Gym",
    location: "вул. Сила, 20, Київ",
    price: "650 грн",
    rating: 4.8,
    features: ["Тренажерний зал", "Силові тренування", "Кардіо"],
    description: "Сучасний тренажерний зал з усім необхідним обладнанням для тренувань.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 23:00",
  },
  {
    name: "Zen Yoga Studio",
    location: "вул. Спокійна, 3, Львів",
    price: "390 грн",
    rating: 4.9,
    features: ["Йога", "Медитація"],
    description: "Затишна студія для практики йоги та медитації.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 21:00",
  },
  {
    name: "Swim & Relax Premium",
    location: "вул. Басейнова, 7, Одеса",
    price: "780 грн",
    rating: 4.6,
    features: ["Басейн", "Сауна"],
    description: "Комплекс з басейном та сауною для повного релаксу.",
    image: "./src/images/gym.jpg",
    hours: "07:00 - 22:00",
  },
  {
    name: "Urban Gym Standard",
    location: "вул. Міська, 10, Київ",
    price: "480 грн",
    rating: 4.7,
    features: ["Тренажерний зал", "Кардіо"],
    description: "Міський спортзал з сучасним обладнанням для тренувань.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 23:00",
  },
  {
    name: "Elite Fitness VIP",
    location: "вул. Елітна, 5, Харків",
    price: "950 грн",
    rating: 4.9,
    features: ["Тренажерний зал", "Спа", "Персональні тренування"],
    description: "Елітний фітнес-клуб з преміальними послугами.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 23:00",
  },
  {
    name: "Family Fitness Plus",
    location: "вул. Родинна, 15, Львів",
    price: "340 грн",
    rating: 4.8,
    features: ["Групові тренування", "Дитячі програми"],
    description: "Фітнес-клуб для всієї родини з програмами для дітей та дорослих.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 21:00",
  },
  {
    name: "AquaFit Premium",
    location: "вул. Водна, 12, Одеса",
    price: "690 грн",
    rating: 4.7,
    features: ["Басейн", "Аквааеробіка"],
    description: "Спортивний комплекс з аквааеробікою та басейном.",
    image: "./src/images/gym.jpg",
    hours: "07:00 - 22:00",
  },
  {
    name: "ProFit Gym Advanced",
    location: "вул. Професійна, 18, Київ",
    price: "570 грн",
    rating: 4.8,
    features: ["Тренажерний зал", "Персональні тренування"],
    description: "Професійний спортзал з індивідуальними тренуваннями.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 23:00",
  },
  {
    name: "Relax & Stretch Pro",
    location: "вул. Релаксна, 9, Львів",
    price: "440 грн",
    rating: 4.9,
    features: ["Йога", "Розтяжка"],
    description: "Студія для занять йогою та розтяжкою.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 21:00",
  },
  {
    name: "SpeedFit Max",
    location: "вул. Швидка, 4, Харків",
    price: "490 грн",
    rating: 4.7,
    features: ["Кардіо", "Силові тренування"],
    description: "Фітнес-клуб для швидких та ефективних тренувань.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 22:00",
  },
  {
    name: "Harmony Studio Deluxe",
    location: "вул. Гармонійна, 6, Одеса",
    price: "680 грн",
    rating: 4.8,
    features: ["Йога", "Медитація", "Спа"],
    description: "Студія для гармонії тіла та душі.",
    image: "./src/images/gym.jpg",
    hours: "09:00 - 20:00",
  },
  {
    name: "Active Life Center",
    location: "вул. Активна, 11, Київ",
    price: "430 грн",
    rating: 4.6,
    features: ["Групові тренування", "Кардіо"],
    description: "Фітнес-клуб для активного способу життя.",
    image: "./src/images/gym.jpg",
    hours: "07:00 - 22:00",
  },
  {
    name: "Body Balance Studio",
    location: "вул. Балансна, 8, Львів",
    price: "460 грн",
    rating: 4.9,
    features: ["Йога", "Пілатес"],
    description: "Студія для досягнення балансу тіла та розуму.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 21:00",
  },
  {
    name: "Energy Gym Plus",
    location: "вул. Енергійна, 14, Харків",
    price: "530 грн",
    rating: 4.7,
    features: ["Тренажерний зал", "Кардіо"],
    description: "Спортзал для енергійних тренувань.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 23:00",
  },
  {
    name: "Aqua Paradise Deluxe",
    location: "вул. Водний рай, 10, Одеса",
    price: "820 грн",
    rating: 4.8,
    features: ["Басейн", "Сауна"],
    description: "Комплекс для водного відпочинку та релаксації.",
    image: "./src/images/gym.jpg",
    hours: "07:00 - 22:00",
  },
  {
    name: "Fit & Fun Express",
    location: "вул. Весела, 7, Київ",
    price: "330 грн",
    rating: 4.6,
    features: ["Групові тренування", "Кардіо"],
    description: "Фітнес-клуб для веселих та ефективних тренувань.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 22:00",
  },
  {
    name: "Zen Balance Club",
    location: "вул. Спокійна, 12, Львів",
    price: "390 грн",
    rating: 4.9,
    features: ["Йога", "Медитація"],
    description: "Студія для досягнення внутрішнього спокою.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 21:00",
  },
  {
    name: "Pro Swim Elite",
    location: "вул. Басейнова, 5, Одеса",
    price: "710 грн",
    rating: 4.7,
    features: ["Басейн", "Аквааеробіка"],
    description: "Комплекс для професійного плавання та аквааеробіки.",
    image: "./src/images/gym.jpg",
    hours: "07:00 - 22:00",
  },
  {
    name: "Urban Fitness Pro",
    location: "вул. Міська, 9, Київ",
    price: "550 грн",
    rating: 4.8,
    features: ["Тренажерний зал", "Кардіо"],
    description: "Міський спортзал з сучасним обладнанням.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 23:00",
  },
  {
    name: "Elite Wellness VIP",
    location: "вул. Елітна, 3, Харків",
    price: "990 грн",
    rating: 4.9,
    features: ["Спа", "Масаж", "Персональні тренування"],
    description: "Елітний центр здоров'я з преміальними послугами.",
    image: "./src/images/gym.jpg",
    hours: "09:00 - 21:00",
  },
  {
    name: "Family Active Basic",
    location: "вул. Родинна, 6, Львів",
    price: "280 грн",
    rating: 4.8,
    features: ["Групові тренування", "Дитячі програми"],
    description: "Фітнес-клуб для всієї родини.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 21:00",
  },
  {
    name: "Aqua World Premium",
    location: "вул. Водна, 15, Одеса",
    price: "760 грн",
    rating: 4.7,
    features: ["Басейн", "Сауна"],
    description: "Комплекс для водного відпочинку.",
    image: "./src/images/gym.jpg",
    hours: "07:00 - 22:00",
  },
  {
    name: "Pro Gym Expert",
    location: "вул. Професійна, 10, Київ",
    price: "600 грн",
    rating: 4.8,
    features: ["Тренажерний зал", "Персональні тренування"],
    description: "Професійний спортзал з індивідуальними тренуваннями.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 23:00",
  },
  {
    name: "Budget Fitness",
    location: "вул. Економна, 5, Київ",
    price: "150 грн",
    rating: 3.8,
    features: ["Тренажерний зал", "Кардіо"],
    description: "Доступний спортзал з базовими тренажерами.",
    image: "./src/images/gym.jpg",
    hours: "07:00 - 22:00",
  },
  {
    name: "Yoga Essential",
    location: "вул. Базова, 8, Львів",
    price: "200 грн",
    rating: 4.0,
    features: ["Йога", "Медитація"],
    description: "Базова студія для практики йоги.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 20:00",
  },
  {
    name: "Aqua Basic",
    location: "вул. Водна, 3, Одеса",
    price: "260 грн",
    rating: 3.9,
    features: ["Басейн", "Аквааеробіка"],
    description: "Базовий комплекс з басейном.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 21:00",
  },
  {
    name: "Power Gym Light",
    location: "вул. Легка, 7, Харків",
    price: "180 грн",
    rating: 3.7,
    features: ["Тренажерний зал", "Силові тренування"],
    description: "Базовий спортзал для силових тренувань.",
    image: "./src/images/gym.jpg",
    hours: "07:00 - 21:00",
  },
  {
    name: "CrossFit Basic",
    location: "вул. Проста, 2, Київ",
    price: "230 грн",
    rating: 4.1,
    features: ["Кросфіт", "Групові тренування"],
    description: "Базовий зал для занять кросфітом.",
    image: "./src/images/gym.jpg",
    hours: "07:00 - 21:00",
  },
  {
    name: "StartFit",
    location: "вул. Початкова, 4, Львів",
    price: "120 грн",
    rating: 3.6,
    features: ["Тренажерний зал", "Кардіо"],
    description: "Стартовий спортзал для початківців.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 20:00",
  },
  {
    name: "Eco Yoga",
    location: "вул. Екологічна, 6, Одеса",
    price: "210 грн",
    rating: 4.2,
    features: ["Йога", "Медитація"],
    description: "Екологічна студія для практики йоги.",
    image: "./src/images/gym.jpg",
    hours: "09:00 - 20:00",
  },
  {
    name: "City Fitness",
    location: "вул. Міська, 12, Київ",
    price: "300 грн",
    rating: 4.3,
    features: ["Тренажерний зал", "Кардіо", "Групові тренування"],
    description: "Міський фітнес-центр з різними програмами.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 22:00",
  },
  {
    name: "Lady Fitness",
    location: "вул. Жіноча, 5, Харків",
    price: "270 грн",
    rating: 4.4,
    features: ["Групові тренування", "Кардіо"],
    description: "Фітнес-клуб для жінок.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 21:00",
  },
  {
    name: "Men's Power",
    location: "вул. Чоловіча, 8, Львів",
    price: "290 грн",
    rating: 4.3,
    features: ["Тренажерний зал", "Силові тренування"],
    description: "Спортзал для чоловіків.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 23:00",
  },
  {
    name: "Aqua Standard",
    location: "вул. Стандартна, 9, Одеса",
    price: "380 грн",
    rating: 4.2,
    features: ["Басейн", "Сауна"],
    description: "Стандартний комплекс з басейном.",
    image: "./src/images/gym.jpg",
    hours: "07:00 - 21:00",
  },
  {
    name: "Minimal Gym",
    location: "вул. Мінімальна, 3, Київ",
    price: "100 грн",
    rating: 3.5,
    features: ["Тренажерний зал"],
    description: "Мінімалістичний спортзал з базовими тренажерами.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 20:00",
  },
  {
    name: "Student Fitness",
    location: "вул. Студентська, 7, Харків",
    price: "140 грн",
    rating: 3.7,
    features: ["Тренажерний зал", "Кардіо"],
    description: "Бюджетний спортзал для студентів.",
    image: "./src/images/gym.jpg",
    hours: "07:00 - 22:00",
  },
  {
    name: "Evening Yoga",
    location: "вул. Вечірня, 5, Львів",
    price: "220 грн",
    rating: 4.1,
    features: ["Йога", "Медитація"],
    description: "Студія йоги з вечірніми заняттями.",
    image: "./src/images/gym.jpg",
    hours: "16:00 - 22:00",
  },
  {
    name: "Morning Swim",
    location: "вул. Ранкова, 6, Одеса",
    price: "310 грн",
    rating: 4.0,
    features: ["Басейн", "Аквааеробіка"],
    description: "Басейн з ранковими заняттями.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 12:00",
  },
  {
    name: "Health Center Basic",
    location: "вул. Здорова, 4, Київ",
    price: "320 грн",
    rating: 4.2,
    features: ["Тренажерний зал", "Масаж"],
    description: "Базовий центр здоров'я з масажними послугами.",
    image: "./src/images/gym.jpg",
    hours: "09:00 - 21:00",
  },
  {
    name: "Simple CrossFit",
    location: "вул. Проста, 7, Харків",
    price: "250 грн",
    rating: 3.9,
    features: ["Кросфіт"],
    description: "Простий зал для кросфіту.",
    image: "./src/images/gym.jpg",
    hours: "07:00 - 21:00",
  },
  {
    name: "Basic Pilates",
    location: "вул. Базова, 9, Львів",
    price: "230 грн",
    rating: 4.0,
    features: ["Пілатес"],
    description: "Базова студія для занять пілатесом.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 20:00",
  },
  {
    name: "Water Relax",
    location: "вул. Водна, 8, Одеса",
    price: "350 грн",
    rating: 4.1,
    features: ["Басейн", "Сауна"],
    description: "Комплекс для водного релаксу.",
    image: "./src/images/gym.jpg",
    hours: "09:00 - 21:00",
  },
  {
    name: "Night Fitness",
    location: "вул. Нічна, 10, Київ",
    price: "240 грн",
    rating: 3.8,
    features: ["Тренажерний зал", "Кардіо"],
    description: "Фітнес-клуб з нічним графіком роботи.",
    image: "./src/images/gym.jpg",
    hours: "22:00 - 06:00",
  },
  {
    name: "Weekend Gym",
    location: "вул. Вихідна, 5, Харків",
    price: "190 грн",
    rating: 3.6,
    features: ["Тренажерний зал", "Групові тренування"],
    description: "Спортзал з розширеним графіком у вихідні.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 22:00",
  },
  {
    name: "Seasonal Fitness",
    location: "вул. Сезонна, 7, Львів",
    price: "280 грн",
    rating: 3.9,
    features: ["Тренажерний зал", "Кардіо"],
    description: "Фітнес-клуб з сезонними програмами.",
    image: "./src/images/gym.jpg",
    hours: "07:00 - 21:00",
  },
  {
    name: "Summer Swim",
    location: "вул. Літня, 9, Одеса",
    price: "400 грн",
    rating: 4.2,
    features: ["Басейн", "Аквааеробіка"],
    description: "Літній басейн з програмами аквааеробіки.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 22:00",
  },
  {
    name: "Winter Gym",
    location: "вул. Зимова, 6, Київ",
    price: "310 грн",
    rating: 4.0,
    features: ["Тренажерний зал", "Кардіо"],
    description: "Зимовий спортзал з опаленням.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 22:00",
  },
  {
    name: "Senior Fitness",
    location: "вул. Досвідчена, 5, Харків",
    price: "220 грн",
    rating: 4.3,
    features: ["Тренажерний зал", "Групові тренування"],
    description: "Фітнес-клуб для людей старшого віку.",
    image: "./src/images/gym.jpg",
    hours: "09:00 - 19:00",
  },
  {
    name: "Junior Gym",
    location: "вул. Молодіжна, 7, Львів",
    price: "170 грн",
    rating: 4.1,
    features: ["Тренажерний зал", "Дитячі програми"],
    description: "Спортзал для молоді та підлітків.",
    image: "./src/images/gym.jpg",
    hours: "10:00 - 20:00",
  },
  {
    name: "Baby Swim",
    location: "вул. Дитяча, 8, Одеса",
    price: "290 грн",
    rating: 4.4,
    features: ["Басейн", "Дитячі програми"],
    description: "Басейн для малюків та дітей.",
    image: "./src/images/gym.jpg",
    hours: "09:00 - 19:00",
  },
  {
    name: "Outdoor Fitness",
    location: "вул. Відкрита, 5, Київ",
    price: "160 грн",
    rating: 3.9,
    features: ["Групові тренування", "Кардіо"],
    description: "Фітнес на відкритому повітрі.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 20:00",
  },
  {
    name: "Indoor Gym",
    location: "вул. Закрита, 7, Харків",
    price: "240 грн",
    rating: 4.0,
    features: ["Тренажерний зал", "Кардіо"],
    description: "Закритий спортзал з кондиціонерами.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 22:00",
  },
  {
    name: "Business Fitness",
    location: "вул. Ділова, 10, Львів",
    price: "470 грн",
    rating: 4.5,
    features: ["Тренажерний зал", "Спа", "Масаж"],
    description: "Фітнес-клуб для ділових людей.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 23:00",
  },
  {
    name: "Economy Swim",
    location: "вул. Економна, 5, Одеса",
    price: "230 грн",
    rating: 3.7,
    features: ["Басейн"],
    description: "Економний басейн для плавання.",
    image: "./src/images/gym.jpg",
    hours: "08:00 - 20:00",
  },
  {
    name: "Premium Fitness",
    location: "вул. Преміум, 8, Київ",
    price: "870 грн",
    rating: 4.9,
    features: ["Тренажерний зал", "Спа", "Масаж", "Персональні тренування"],
    description: "Преміальний фітнес-клуб з усіма послугами.",
    image: "./src/images/gym.jpg",
    hours: "06:00 - 23:00",
  },
  {
    name: "Basic Gym",
    location: "вул. Базова, 4, Харків",
    price: "130 грн",
    rating: 3.5,
    features: ["Тренажерний зал"],
    description: "Базовий спортзал з тренажерами.",
    image: "./src/images/gym.jpg",
    hours: "07:00 - 21:00",
  },
];
